In [24]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

In [25]:
df = pd.read_csv("mabel.txt",header=None,on_bad_lines='skip',encoding='utf8')

In [26]:
df =df.drop(0)
df.columns = ["Date","Chat"]
Message = df["Chat"].str.split("-",n=1,expand = True)
df["Time"]= Message[0]
Message1 = Message[1].str.split(":",n=1,expand = True)
df["Name"]= Message1[0]
df["Chat"]= Message1[1]
df = df[["Date","Time","Name","Chat"]]

In [27]:
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [28]:
#Sentiment Analysis
dataset = df
dataset.dropna(inplace= True)

sid = SentimentIntensityAnalyzer()
senti = sid.polarity_scores(dataset['Chat'][4])
senti

{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.296}

In [29]:
def sentimentAnalysis(data, columnname):
    import matplotlib.pyplot as plt
    import seaborn as sns
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    
    sid = SentimentIntensityAnalyzer()

    data.dropna(inplace = True)

    data['score']    = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
    data['compound'] = data['score'].apply(lambda score_dict: score_dict['compound'])
    data['negative'] = data['score'].apply(lambda score_dict: score_dict['neg'])
    data['positive'] = data['score'].apply(lambda score_dict: score_dict['pos'])
    data['neutral']  = data['score'].apply(lambda score_dict: score_dict['neu'])

    data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c>= 0 else 'neg')
    plt.clf()

    posneg = pd.DataFrame(data['comp_score'].value_counts())
    return posneg,data

In [30]:
pos, data_senti = sentimentAnalysis(dataset, columnname = 'Chat')

In [31]:
data_senti

,Date,Time,Name,Chat,score,compound,negative,positive,neutral,comp_score
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos

In [32]:
#Topic modelling
tfidf = TfidfVectorizer(stop_words='english')
dtm = tfidf.fit_transform(df["Chat"])
dtm

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 188 stored elements and shape (50, 122)>

In [33]:
nmf_model = NMF(n_components = 5,random_state = 42)
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

In [34]:
for index,topic in enumerate (nmf_model.components_):
    results = ([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print(results)

['updates', 'okay', 'free', 'cal', 'kk', 'read', 'abstract', 'sure', 'yeah', 'mam']
['hi', 'financial', 'finalization', 'send', 'just', 'know', 'tomorrow', 'mam', 'thank', 'ok']
['start', 'details', 'abstracts', 'students', 'phone', 'ask', 'office', 'vignesh', 'number', 'send']
['plan', 'night', 'late', 'spoke', 'mabel', 'just', 'couldn', 'tomorrow', 'church', 'hi']
['talk', '30', 'today', 'rani', '7pm', 'ya', 'details', 'ramisha', 'need', 'yes']

In [35]:
topic_results = nmf_model.transform(dtm)
df["Topic"]   = topic_results.argmax(axis = 1)

In [36]:
df

,Date,Time,Name,Chat,score,compound,negative,positive,neutral,comp_score,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos,4
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,0
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos,2
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos,0
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos,2
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos,0
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,1
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos,4
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos,0
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos,3
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos,2
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg,4
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos,0
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg,4
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos,2
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos,0
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos,0
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos,0
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos,2
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos,0

In [37]:
#Flirt prediction

flirt_words=['babe', 'baby', 'honey', 'cutie', 'crush', 'sexy', 'beautiful', 'handsome', 'gorgeous', 'cute', 'hot', 
             'hang out', 'meet up', 'date', 'alone', 'just us', 'tonight', 'cal u', 'are u free', 'location']
flirt_set = set(flirt_words)

def check_for_flirtword(data,columnname):
    df['flirt_message'] = df[columnname].apply(lambda x: 'Yes' if set(str(x).lower().split()) & flirt_set else 'No')                
    flirt = pd.DataFrame(data['flirt_message'])   
    return data, flirt

In [38]:
data,flirt = check_for_flirtword (dataset, 'Chat')
data

,Date,Time,Name,Chat,score,compound,negative,positive,neutral,comp_score,Topic,flirt_message
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3,No
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1,No
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos,4,No
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,0,No
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos,2,No
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos,0,No
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1,No
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos,2,Yes
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos,0,No
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,1,No
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos,4,No
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos,0,No
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3,No
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos,3,No
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos,2,No
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg,4,No
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos,0,No
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3,No
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg,4,Yes
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos,1,No
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4,No
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos,2,No
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos,0,No
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1,No
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos,0,No
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3,No
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos,0,No
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3,No
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0,No
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2,No
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos,2,No
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos,0,No

Who is talkative ?

In [40]:
talkative = (dataset['Name'].value_counts().idxmax()).upper()
print("More Talktative:", talkative)

less_Talktative = (dataset['Name'].value_counts().idxmin()).upper()
print("Less Talktative:", less_Talktative)

More Talktative:  AR❤
Less Talktative:  MABEL INFOZIANT

Most active date & time

In [42]:
most_active_date = dataset["Date"].value_counts().idxmax()
print("Most active date:", most_active_date)

most_active_time = dataset["Time"].value_counts().idxmax()
print("Most Active Time:", most_active_time)

Most active date: 05/12/19
Most Active Time:  1:43 pm

Message count sent by each user

In [44]:
media =dataset[dataset["Chat"] == " <media omitted>"]

if len(media):
    media_count = pd.DataFrame(media["Name"].value_counts())
    media_share = media["Name"].value_counts().idxmax()
else:
    media_count = "0"
    media_share = "No Media were shared"
    
print("media_count shared:", media_count)
print("Who shared maximum media:", media_share)

media_count shared: 0
Who shared maximum media: No Media were shared

Missed calls

In [46]:
missed_call = dataset[dataset["Chat"] == "missed voice call"]

if len(missed_call):
    missedcall_count = pd.DataFrame(missed_call["Name"].value_counts())
    Maximum_missed_call = missed_call["Name"].value_counts().idxmax()
else:
    missedcall_count = "0"
    maximum_missed_call = "No missed voice call"
    
print("Total missed calls:", missedcall_count)
print("Most missed calls from:", maximum_missed_call)

Total missed calls: 0
Most missed calls from: No missed voice call

In [ ]:
Missed video calls

In [47]:
missed_video_call =dataset[dataset["Chat"] == "missed video call"]

if len(missed_video_call):
    missedcall_count = pd.DataFrame(missed_video_call["Name"].value_counts())
    Maximum_missed_call = missed_video_call["Name"].value_counts().idxmax()
else:
    missedcall_count = "0"
    maximum_missed_call = "No missed video call"
    
print("Total missed video call:",missedcall_count)
print("Most video missed calls from:", maximum_missed_call)

Total missed video call: 0
Most video missed calls from: No missed video call